import React from "react";

class Loading extends React.Component {
  constructor(props) {
    super(props);
    this.loadColorsAnimation = this.loadColorsAnimation.bind(this);
    this.state = {
      image: "",
      loading: this.props.loading,
    };
    //latest set: Time Spiral Remastered https://mtgjson.com/downloads/all-sets/
    var expansionSets = [
      "arn",
      "atq",
      "leg",
      "drk",
      "fem",
      "hml",
      "ice",
      "all",
      "csp",
      "mir",
      "vis",
      "wth",
      "tmp",
      "sth",
      "exo",
      "usg",
      "ulg",
      "uds",
      "mmq",
      "nem",
      "pcy",
      "inv",
      "pls",
      "apc",
      "ody",
      "tor",
      "jud",
      "ons",
      "lgh",
      "scg",
      "mrd",
      "dst",
      "5dn",
      "chk",
      "bok",
      "sok",
      "rav",
      "gpt",
      "dis",
      "tsp",
      "plc",
      "fut",
      "lrw",
      "mor",
      "shm",
      "eve",
      "ala",
      "con",
      "arb",
      "zen",
      "wwk",
      "roe",
      "som",
      "mbs",
      "nph",
      "isd",
      "dka",
      "avr",
      "rtr",
      "gtc",
      "dgm",
      "ths",
      "bng",
      "jou",
      "ktk",
      "frf",
      "dtk",
      "bfz",
      "ogw",
      "soi",
      "emn",
      "kld",
      "aer",
      "akh",
      "hou",
      "xln",
      "rix",
      "dom",
      "grn",
      "rna",
      "war",
      "eld",
      "thb",
      "iko",
      "ZNR",
    ];
    var otherSets = [
      "lea",
      "leb",
      "2ed",
      "3ed",
      "4ed",
      "5ed",
      "6ed",
      "7ed",
      "8ed",
      "9ed",
      "10e",
      "m10",
      "m11",
      "m12",
      "m13",
      "m14",
      "m15",
      "ori",
      "m19",
      "m20",
      "m21",
      "hop",
      "arc",
      "cmd",
      "pc2",
      "cm1",
      "c13",
      "c14",
      "c15",
      "c16",
      "c17",
      "c18",
      "c19",
      "c20",
      "cns",
      "cn2",
      "pca",
      "cma",
      "e01",
      "e02",
      "cm2",
      "bbd",
      "chr",
      "ath",
      "brb",
      "btd",
      "dkm",
      "mma",
      "mm2",
      "ema",
      "mm3",
      "ima",
      "a25",
      "uma",
      "mh1",
      "por",
      "p02",
      "ptk",
      "s99",
      "s00",
      "w16",
      "w17",
      "evg",
      "dd2",
      "ddc",
      "ddd",
      "dde",
      "ddf",
      "ddg",
      "ddh",
      "ddi",
      "ddj",
      "ddk",
      "ddl",
      "ddm",
      "ddn",
      "ddo",
      "ddp",
      "ddq",
      "ddr",
      "dds",
      "ddt",
      "ddu",
      "drb",
      "v09",
      "v0x",
      "v10",
      "v11",
      "v12",
      "v13",
      "v14",
      "v15",
      "v16",
      "v17",
      "h09",
      "pd2",
      "pd3",
      "md1",
      "ugl",
      "unh",
      "ust",
      "und",
      "J20",
      "JMP",
      "2XM",
      "CMR",
      "CC1",
      "TSR",
    ];
    this.sets = expansionSets.concat(otherSets);
  }

  componentDidMount() {
    this.loadColorsAnimation();
  }

  componentWillUnmount() {
    clearTimeout(this.timer);
    this.setState({ loading: false });
  }

  loadColorsAnimation() {
    var imageCode = this.sets[Math.floor(Math.random() * this.sets.length)];
    this.setState({
      image: imageCode,
    });
    this.timer = setTimeout(() => {
      this.loadColorsAnimation();
    }, 1500);
  }

  render() {
    return (
      <div className="loadingText">
        <h1>Shuffling...</h1>
        <h1>
          <i className={"ss ss-" + this.state.image + " ss-6x"}></i>
        </h1>
      </div>
    );
  }
}

export default Loading;
