name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.19.1
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.1

      - name: Install dependencies
        run: npm ci
        working-directory: mtgv-api

      - name: Run linter
        run: npm run lint
        working-directory: mtgv-api

      - name: Run tests
        run: npm test
        working-directory: mtgv-api 